### ISSUE TITLE
Wrong CVC validation for AmEx

### ISSUE THREAD

**Issue by vkurlyan** [Adyen/CSE-JS#24] opened 2016-06-17 15:36 UTC
Invalid CVC input has 'valid' class until onblur event fired on them.

**Steps to reproduce:**
1) Fill 3 digits to CVC
2) Fill valid AmEx card number (example: 3700 0000 0000 002)
**Actual result:** CVC input has valid class but form can't be submited.
**Expecting result:** CVC input has error class.

It would be understandable for user to see that CVC is invalid for AmEx card.
_Note: fourDigitCvcForBins has default value - '34,37'_

**Comment by ArnoudAdyen** [comment] 2016-06-22 12:49
From what I can tell the root cause is the same as for issue #21. I'll close this one, and keep status in that issue.

**Closed as completed by ArnoudAdyen** 2016-06-22 12:49 UTC
