### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by voronianski** [Adyen/CSE-JS#40] opened 2016-10-20 14:13 UTC
In latest test CSE SDK there is a syntax error that breaks the whole functionality. Link that we use `https://test.adyen.com/hpp/cse/js/<OUR CLIENT ID>.shtml`, screenshot of source code:

![image](https://cloud.githubusercontent.com/assets/974035/19563355/e9da9f06-96df-11e6-9582-ca953e7787fc.png)

**Comment by ArnoudAdyen** [comment] 2016-10-20 15:28
Hi,

My apology for the delay. The issue is being fixed at the moment. Please make sure to always also send a ticket to Adyen support in case you notice this as that channel is monitored more tightly than the github issue list.

Note that the live versions of the CSE SDK was not affected by today's patch and still remains on 0.1.18 and did not suffer from this error.

I will update / close this issue once the merchant test servers are patched.

**Comment by voronianski** [comment] 2016-10-20 15:39
@ArnoudAdyen unfortunately there is another syntax error:

```
Uncaught SyntaxError: Unexpected token )
```

![image](https://cloud.githubusercontent.com/assets/974035/19566876/1858e908-96ec-11e6-8072-1d1a237077ec.png)

**Comment by ArnoudAdyen** [comment] 2016-10-20 17:01
Hi.

Yes. The fix forward failed, so we are rolling back to only offer 0_1_18 on the hosted CSE so we have more time on investigating what is going on with 0_1_19. 
- Arnoud

**Comment by ArnoudAdyen** [comment] 2016-10-24 09:41
Closing this issue for now as the rollback was completed on thursday

**Closed as completed by ArnoudAdyen** 2016-10-24 09:41 UTC
